
# establish models

mkdir 03_establish_models
nohup Rscript 00_analysis_code/02.1_compute_weights_cis_trans.R --geno_Typed 01_preprocess_data/AFA/Genotyped/ --geno_Imputed 01_preprocess_data/AFA/Imputed/ --GRCh_version 38 --hyphen : --ethnic Afa --pheno 01_preprocess_data/phenotype/Soma_SMP.txt --covariate 01_preprocess_data/covariate/covariate_for_AFA_male.txt --annotation 01_preprocess_data/annotation/SomaScan_TSS.txt --trans_threshold 5e-9 --ref_ld /data/sliu/database/LD-reference/LD_ref/AFR_male --out 03_establish_models/AFR_male_5e-9 >> 03_establish_models.log&
nohup Rscript 00_analysis_code/02.1_compute_weights_cis_trans.R --geno_Typed 01_preprocess_data/CAU/Genotyped/ --geno_Imputed 01_preprocess_data/CAU/Imputed/ --GRCh_version 38 --hyphen : --ethnic Eur --pheno 01_preprocess_data/phenotype/Soma_SMP.txt --covariate 01_preprocess_data/covariate/covariate_for_CAU_male.txt --annotation 01_preprocess_data/annotation/SomaScan_TSS.txt --trans_threshold 5e-9 --ref_ld /data/sliu/database/LD-reference/LD_ref/EUR_male --out 03_establish_models/CAU_male_5e-9 >> 03_establish_models.log&
nohup Rscript 00_analysis_code/02.1_compute_weights_cis_trans.R --geno_Typed 01_preprocess_data/CHN/Genotyped/ --geno_Imputed 01_preprocess_data/CHN/Imputed/ --GRCh_version 38 --hyphen : --ethnic Chn --pheno 01_preprocess_data/phenotype/Soma_SMP.txt --covariate 01_preprocess_data/covariate/covariate_for_CHN_male.txt --annotation 01_preprocess_data/annotation/SomaScan_TSS.txt --trans_threshold 5e-9 --ref_ld /data/sliu/database/LD-reference/LD_ref/EAS_male --out 03_establish_models/CHN_male_5e-9 >> 03_establish_models.log&
nohup Rscript 00_analysis_code/02.1_compute_weights_cis_trans.R --geno_Typed 01_preprocess_data/HIS/Genotyped/ --geno_Imputed 01_preprocess_data/HIS/Imputed/ --GRCh_version 38 --hyphen : --ethnic His --pheno 01_preprocess_data/phenotype/Soma_SMP.txt --covariate 01_preprocess_data/covariate/covariate_for_HIS_male.txt --annotation 01_preprocess_data/annotation/SomaScan_TSS.txt --trans_threshold 5e-9 --ref_ld /data/sliu/database/LD-reference/LD_ref/AMR_male --out 03_establish_models/HIS_male_5e-9 >> 03_establish_models.log&
Rscript 00_analysis_code/02.2_model_performance.R

# association

#association for prostate cancer 2023 NG
nohup Rscript 00_analysis_code/03.1_association_test_cis_trans.R --sumstats /data/sliu/database/GWAS_summary/prostate_multiethnic_2023_NG_Anqi/prostate_African_American_2023_NG.txt --pos_dir 03_establish_models/AFR_male_5e-9/08_establish_prediction_models/pos/ --model_dir 03_establish_models/AFR_male_5e-9/08_establish_prediction_models/models/ --ref_ld_dir 03_establish_models/AFR_male_5e-9/08_establish_prediction_models/ref_ld/ --TSS 01_preprocess_data/annotation/SomaScan_TSS.txt --output_dir 04_association/association_prostate_cancer_2023_NG_AFA > 04_association.log&
nohup Rscript 00_analysis_code/03.1_association_test_cis_trans.R --sumstats /data/sliu/database/GWAS_summary/prostate_multiethnic_2023_NG_Anqi/prostate_East_Asian_2023_NG.txt --pos_dir 03_establish_models/CHN_male_5e-9/08_establish_prediction_models/pos/ --model_dir 03_establish_models/CHN_male_5e-9/08_establish_prediction_models/models/ --ref_ld_dir 03_establish_models/CHN_male_5e-9/08_establish_prediction_models/ref_ld/ --TSS 01_preprocess_data/annotation/SomaScan_TSS.txt --output_dir 04_association/association_prostate_cancer_2023_NG_CHN >> 04_association.log&
nohup Rscript 00_analysis_code/03.1_association_test_cis_trans.R --sumstats /data/sliu/database/GWAS_summary/prostate_multiethnic_2023_NG_Anqi/prostate_European_2023_NG.txt --pos_dir 03_establish_models/CAU_male_5e-9/08_establish_prediction_models/pos/ --model_dir 03_establish_models/CAU_male_5e-9/08_establish_prediction_models/models/ --ref_ld_dir 03_establish_models/CAU_male_5e-9/08_establish_prediction_models/ref_ld/ --TSS 01_preprocess_data/annotation/SomaScan_TSS.txt --output_dir 04_association/association_prostate_cancer_2023_NG_CAU >> 04_association.log&
nohup Rscript 00_analysis_code/03.1_association_test_cis_trans.R --sumstats /data/sliu/database/GWAS_summary/prostate_multiethnic_2023_NG_Anqi/prostate_Hispanic_2023_NG.txt --pos_dir 03_establish_models/HIS_male_5e-9/08_establish_prediction_models/pos/ --model_dir 03_establish_models/HIS_male_5e-9/08_establish_prediction_models/models/ --ref_ld_dir 03_establish_models/HIS_male_5e-9/08_establish_prediction_models/ref_ld/ --TSS 01_preprocess_data/annotation/SomaScan_TSS.txt --output_dir 04_association/association_prostate_cancer_2023_NG_HIS >> 04_association.log&

Rscript 00_analysis_code/03.2_association_test_FDR.R


